### ISSUE TITLE
Set-up del proyecto

### ISSUE THREAD

**Issue by amedesc** [amedesc/mantsoft-fidu-2019#1]
1. Instalar la última versión de Python 3 de https://www.python.org/ (instalación por defecto). Aquí se instalará Python y IDLE - el editor de código en python que vamos a usar.
3. Clonar este repositorio desde GitHub Desktop (investigar cómo hacerlo, pero es bastante intuitivo)

**Comment by amedesc** [comment]
**Por fa no mover de columna las tarjetas con la etiqueta general**

**Comment by jpablogz** [comment]
Resuelto.
