### ISSUE TITLE
Crear el Release #1 

### ISSUE THREAD

**Issue by amedesc** [amedesc/mantsoft-fidu-2019#40]
Ahora que tuvimos la primera entrega de nuestro proyecto, podemos hacer nuestro primer lanzamiento o release en GitHub.

1. En GitHub web ir a Code > Releases y crear un nuevo release.
2. El realease debe tener el número de versión 0.1 y de nombre "Semana 1". 
3. El release debe tener una descripción que resuma qué se hizo esta semana. 

Podés comentar en esta tarea el url al release.

**Comment by Stevaguilar** [comment]
> Ahora que tuvimos la primera entrega de nuestro proyecto, podemos hacer nuestro primer lanzamiento o release en GitHub.
> 
> 1. En GitHub web ir a Code > Releases y crear un nuevo release.
> 2. El realease debe tener el número de versión 0.1 y de nombre "Semana 1".
> 3. El release debe tener una descripción que resuma qué se hizo esta semana.
> 
> Podés comentar en esta tarea el url al release.

Url del release 0.1: https://github.com/amedesc/mantsoft-fidu-2019/releases/tag/0.1

**Comment by amedesc** [comment]
@Stevaguilar este Release corresponde al de la semana pasada. Es decir, debería describir lo que hicimos la semana pasada y no lo que estamos haciendo esta semana.

**Comment by Stevaguilar** [comment]
Ya se actualizó la descripcion

**Comment by amedesc** [comment]
@Stevaguilar Listo! Gracias!
